### ISSUE TITLE
Execution bug report 

### ISSUE THREAD

**Issue by Trwang9201** [issp-center-dev/abICS#26]
Hi, guys 

Here are some issues reported which I try to run the example (VASP version).

**_Input files_**: all the example file you supplied except
[solver]
type = 'vasp'
path = '/usr/bin/vasp_std'
base_input_dir = '/home/wangtairan/download/abICS-master/examples/standard/spinel/baseinput'
perturb = 0.1

**_Output_**: 
Traceback (most recent call last):
  File "_mt19937.pyx", line 178, in numpy.random._mt19937.MT19937._legacy_seeding
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/abics", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/abics/scripts/main.py", line 139, in main
    main_impl(tomlfile)
  File "/usr/local/lib/python3.6/dist-packages/abics/scripts/main.py", line 50, in main_impl
    comm = RX_MPI_init(rxparams)
  File "/usr/local/lib/python3.6/dist-packages/abics/mc_mpi.py", line 143, in RX_MPI_init
    rand.seed(rand_seeds[worldrank])
  File "mtrand.pyx", line 244, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 186, in numpy.random._mt19937.MT19937._legacy_seeding
TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'

Thank you guys!

**Comment by skasamatsu** [comment]
Hi! Thank you for the report!
We had fixed this in the development branches but hadn't merged it.
We merged a fix into the release-v1.0 branch so please have a try.
https://github.com/issp-center-dev/abICS/tree/release-v1.0

A workaround on the old version (master branch) is to specify a random number seed. For example:
[replica]
seed=12345

Also, the VASP version won't run correctly without a patch to VASP (we're asking VASP folks if we can distribute it). In the meanwhile, maybe you can try out the QE version?
